# A list with all the commands sent to the robot
CommandList commands
---
# The result with a result code, the command id and additional information
Result result
---
# Feedback is the same message as result
Result feedback
